version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--entryPoints.https.tls=true"
      - "--entryPoints.https.certificates=/etc/traefik/certificates/certificate.pem,/etc/traefik/certificates/private.key"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/etc/traefik/certificates
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml


  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    expose:
      - "8001"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-server.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.services.api-server.loadbalancer.sticky.cookie=true
      - traefik.http.routers.api-server.entrypoints=https
      - traefik.http.routers.api-server.tls=true

  static-server:
    build:
      context: ./static-server
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    expose:
      - "80"
      - "443" 
    labels:
      - traefik.enable=true
      - traefik.http.routers.static-server.rule=Host(`localhost`)
      - traefik.http.routers.static-server.entrypoints=https
      - traefik.http.routers.static-server.tls=true
